version: "3.8"
services:
  #######################################
  # Nginx
  #######################################
  nginx:
    image: nginx:alpine
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /data/www:/data/www
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
      - redis
      - mongodb
      - rabbitmq
      - portainer
    depends_on:
      - mysql
      - redis
      - mongodb
      - rabbitmq
      - portainer
    environment:
      - NGINX_HOST=www.test.lan
      - NGINX_PORT=80
      - RACK_ENV=development
    extra_hosts:
      - "somehost:162.242.195.82"
      - "otherhost:50.31.209.229"

  #######################################
  # PHP74
  #######################################
  php:
    image: php:7.4-fpm
    build: ./php
    ports:
      - "9000"
    volumes:
      - /data/www:/data/www
      - ./php/logs:/var/log
    links:
      - mysql
      - redis
      - mongodb
      - rabbitmq

  #######################################
  # Mysql
  #######################################
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/data:/var/lib/mysql-files
      - ./mysql/log:/var/log/mysql
  #######################################
 
 
  #######################################
  # Redis
  #######################################
  redis:
    image: redis:latest
    container_name: redis
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/logs/:/var/log/redis
    environment:
      - appendonly=root # 打开redis密码设置
      - requirepass=123456 # 设置redis密码
      
  #######################################
  # MongoDB
  #######################################
  mongodb:
    build: ./mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo/data:/data/db
      
  #######################################
  # rabbitmq
  #######################################
  rabbitmq:
    #容器名称
    container_name: rabbitmq
    build: ./rabbitmq
    #总是重启后启动
    restart: always
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 25672:25672
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456    
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq/logs
      
  #######################################
  # portainer
  #######################################
  portainer:
    image: portainer/portainer
    #command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9999:9999
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer/data:/data
      